# Generated by Django 4.2.1 on 2023-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaries',
            name='writer',
            field=models.CharField(default='NotFound', max_length=20),
            preserve_default=False,
        ),
    ]
